# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d3c30ad68d142a2b0133209d1c95fa19efdd4cd6ddfe81e12cd43abeeb6f9994019e1eeaaea2e4ae272c209afa7544f1a9b7a7b33d2e708eec34aa79686f704

test:
  secret_key_base: eeb4a55069b905396d94ae89ecb1761555e29e9c6cebfabf98de1a326b42c5b4107c2dd8f5821c03488764036683bcae677cbb703851e668351a8f85cbfe39b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
